### ISSUE TITLE
fsqlite-types 0.1.7 breaks downstream builds that resolve asupersync 0.3.2 (over-broad `^0.3.1`; regression vs 0.1.5)

### ISSUE THREAD

**Issue by Dicklesworthstone** [Dicklesworthstone/frankensqlite#108]
## Summary

`fsqlite-types` 0.1.7 (and current `main`) calls **asupersync 0.3.1's** `NativeCx::for_request_with_budget` (`crates/fsqlite-types/src/cx.rs:662`), which was **renamed to `scope_with_budget` in asupersync 0.3.2**. But the workspace declares `asupersync = "0.3.1"` (i.e. `^0.3.1`), which *allows* 0.3.2. Any downstream that resolves asupersync **0.3.2** (the max in `^0.3.1`, and **not yanked**) fails to compile:

```
error[E0599]: no function or associated item named `for_request_with_budget` found for struct `NativeCx`
  --> fsqlite-types-0.1.7/src/cx.rs:662
  help: there is a method `scope_with_budget` with a similar name
```

The frankensqlite workspace doesn't catch this because its own `Cargo.lock` pins asupersync **0.3.1**. The bug only surfaces in a fresh downstream resolution.

## This is a regression vs 0.1.5

`fsqlite-types` **0.1.5** compiled cleanly against asupersync **0.3.2** (verified: `meta_skill` `main` builds with `fsqlite 0.1.5` + `asupersync 0.3.2`). The breaking call was introduced **after** 0.1.5 by `2e553a97` ("feat(types): replace boolean e-process samples with structured signals and decision artifacts"), which added the `for_request_with_budget` call. So 0.1.7 regressed asupersync-0.3.2 compatibility.

## Why a plain `=0.3.1` pin isn't a clean fix

Pinning `asupersync = "=0.3.1"` forces downstreams to 0.3.1, but **asupersync 0.3.1 itself fails to compile** against the `franken-decision` version a fresh resolve picks:

```
error[E0609]: no field `action_index` on type `Result<DecisionOutcome, ValidationError>`
  --> asupersync-0.3.1/src/runtime/scheduler/three_lane.rs:3207
```

So the real fix is to make `fsqlite-types` compatible with the asupersync version the ecosystem actually resolves (**0.3.2**) — i.e. migrate `cx.rs:662` from `for_request_with_budget` → the 0.3.2 `scope_with_budget` (`NativeCx`) API — and bump the workspace asupersync pin accordingly (mind the 0.3.2 parking caveat: keep `enable_parking(false)`), then cut a 0.1.8.

## Impact

- Fresh `cargo add fsqlite` (resolves asupersync 0.3.2) → **does not compile**.
- Existing consumers survive only because their lockfiles pin asupersync 0.3.1 (beads_rust, cass do).
- Blocks bumping `meta_skill` to `fsqlite 0.1.7` (dependabot PRs).

## Repro

```bash
cargo new fsq-repro && cd fsq-repro
cargo add fsqlite --features fts5     # resolves asupersync 0.3.2
cargo build                            # E0599 on for_request_with_budget
```

_Filed during downstream triage; the 0.1.7 MVCC #106 + FTS5 fixes themselves are good — this is purely the asupersync API/version-range mismatch._

**Comment by Dicklesworthstone** [comment]
Fixed in 57e89a94, released as fsqlite workspace 0.1.8 (7c2a251e, tag v0.1.8) — and **fsqlite-types 0.1.8 is published on crates.io**, so this resolves automatically for downstreams.

Root cause was exactly as you diagnosed: `fsqlite-types` minted an asupersync request context via `for_request_with_budget`, a `test-internals` constructor removed in asupersync 0.3.2, while declaring `asupersync ^0.3.1` (which resolves up to 0.3.2). 57e89a94 cfg-gates that call to `#[cfg(all(feature = "native", test))]` so production builds never touch the test-only API, and 0.1.8 declares `asupersync ^0.3.2` to match what the ecosystem resolves.

No facade republish is needed: every `fsqlite` 0.1.7 sub-crate depends on `fsqlite-types ^0.1.7` (caret, not `=`), so 0.1.8 is pulled automatically. Verified just now with a fresh resolve of a crate depending on `fsqlite = \"0.1.7\"`:

```
fsqlite-types   -> 0.1.8
asupersync      -> 0.3.2
franken-decision-> 0.3.2
```

If you have a Cargo.lock pinning the broken 0.1.7, run `cargo update -p fsqlite-types` to pick up 0.1.8. Thanks for the precise report.

**Comment by Dicklesworthstone** [comment]
Confirming this is now **released**, not just committed: the `57e89a94` fix shipped in **fsqlite 0.1.8** (full-workspace crates.io release, 24 crates, tag `v0.1.8`).

Acceptance test for the exact failure scenario in this issue:
```
cargo new fsq-accept && cd fsq-accept
cargo add fsqlite@0.1.8 --features fts5     # fresh resolve → asupersync 0.3.2 (not yanked)
cargo +nightly check
    Checking fsqlite-core v0.1.8
    Checking fsqlite v0.1.8
    Checking accept v0.1.0
    Finished `dev` profile target(s)          # ✅ compiles
```

A fresh `cargo add fsqlite` resolves **asupersync 0.3.2** and compiles cleanly — the case that failed with `E0599 ... for_request_with_budget` on 0.1.7. Downstreams pinned to `asupersync = "=0.3.1"` as a workaround can move to `fsqlite 0.1.8` and drop the pin.
